### ISSUE TITLE
Test for Environment Variables fails

### ISSUE THREAD

**Issue by aBega2000** [devonfw/IDEasy#239] opened 2024-03-03 19:47 UTC
### Expected behavior

As a IDEasy user, I want the tests to be successful so that everything can run smoothly

### Actual behavior

While running mvn package, trying to package the necessary files, all tests were running, but there was a failure. Namely:

Expected:
C:\WINDOWS\System32\WindowsPowerShell\v1.0;
C:\WINDOWS\System32\OpenSSH;

Actual:
C:\WINDOWS\System32\WindowsPowerShell\v1.0\\;
C:\WINDOWS\System32\OpenSSH\\;

As one can see, the only difference in these two cases, is the \ in the end. This error keeps happening even in other cases, as shown below: 

 
![Screenshot 2024-02-29 180102](https://github.com/devonfw/IDEasy/assets/145266540/5d5ddefe-7798-42e3-8134-67eb0c9c7056)

By comparing them, the result is as follows: 

![Screenshot 2024-02-29 180421](https://github.com/devonfw/IDEasy/assets/145266540/f72ea369-d719-40dc-8345-9bdb707d5f17)

### Steps to reproduce (bug)

1.  Run the command mvn test or mvn package in the terminal, in the folder cli where the pom.xml is located

### Affected version:

* OS: Windows/Linux

 Still haven't tried in Mac

**Comment by hohwille** [comment] 2024-03-08 10:52
Thanks for filing this bug and providing the details for analysis.
I do not have this but as it seems, I could most likely remove trailing slashes from entries in my PATH to reproduce it.

As a solution the `IdeContextTest` should be improved to normalize the PATH entries before comparing. Trailing slashes should be considered as invariant so by consistently removing (or adding) them to both the expected and the actual value the assertion should be fixed easily.

**Comment by CREITZ25** [comment] 2024-03-15 10:24
I tested all combinations and was able to reproduce the problem:
If a part of the path ends with "/" the command
mvn test
runs into errors. However, if you call the command as a parameter from devon,
devon mvn test
then the error no longer occurs.

**Comment by hohwille** [comment] 2024-03-15 11:36
> I tested all combinations and was able to reproduce the problem: If a part of the path ends with "/" the command mvn test runs into errors. However, if you call the command as a parameter from devon, devon mvn test then the error no longer occurs.

Thanks for testing. The reason for this is IMHO because `devon` already updates and normalizes the `PATH` removing trailing slashes so it acts as a workaround for the problem.
However, as I stated above the bug is that our assertion in the test is wrong and the problem is neither caused by `maven` nor by `devon` (devonfw-ide).

**Comment by hohwille** [comment] 2024-03-15 11:40
Here is the bug:
https://github.com/devonfw/IDEasy/blob/8e44c02fffb25707b176042d53d4c564113fc0f0/cli/src/test/java/com/devonfw/tools/ide/context/IdeContextTest.java#L42-L45

IMHO it is very easy to fix. Ideally we can reuse some code from `SystemPath` for the normalization but the most simple fix would be to use some String replacement before the `endsWith` assertion (e.g. a regex `[/\]([:;])` replacement with `$1`).

**Closed** 2024-04-09 12:59 UTC
Labels: bug
