### ISSUE TITLE
Zip Extractions seems to fail in unit tests on Mac OS

### ISSUE THREAD

**Issue by MustaphaOuchen** [devonfw/IDEasy#196] opened 2024-02-06 09:04 UTC
### Expected behavior

Extraction of downloaded "InstallCommandlet"-Applications should work OS independently.

### Actual behavior
It fails with an error, the error message mentions that an IllegalState occurred

### Steps to reproduce (bug)

1. Create a project environment with devonfw on a Mac
2. Clone IDEasy in workspaces/main
3. Navigate via terminal to the IDEasy project folder
4. run 'devon mvn test -Dtest=" InstallCommandletTest"' or 'devon mvn test -Dtest="JmcTest"'

### Comments/Hints:

Failed test error messages look like this:

![Image](https://github.com/devonfw/IDEasy/assets/98693422/bdd8660e-2cf2-466e-a01f-89346e666f94)

### Affected version:

* OS: Mac

**Comment by hohwille** [comment] 2024-08-09 08:56
Seems to be related or duplicate of #452

**Closed** 2024-08-09 08:57 UTC
Labels: bug, duplicate, macOS
