### ISSUE TITLE
Dotnet on Mac x64 is not working properly

### ISSUE THREAD

**Issue by janvcap-mac** [devonfw/IDEasy#866] opened 2024-12-06 15:01 UTC
### Expected behavior

As a < type of user >, I want < some goal > so that < some reason >

### Actual behavior
```
bash-3.2$ ide dotnet
Trying to download dotnet-6.0.428-mac-x64.tar.gz from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.428/dotnet-sdk-6.0.428-osx-x64.tar.gz
Downloading 100% │█████████████████████│ 178/178MiB (0:07:28 / 0:00:00) ,4MiB/s
Checksum da1fde6896a4d84dfa8024fab1abe54a56e02899b85a8600c2ed16ece0543562 is correct.
Extracting TAR file /Users/Username/Downloads/ide/default/dotnet-6.0.428-mac-x64.tar.gz to /Users/Username/IdeasyTestProjects/_ide/tmp/extract-dotnet-6.0.428-mac-x64.tar.gz
Extracting 100% │████████████████████│ 178/178MiB (0:00:06 / 0:00:00) 29,7MiB/s
Successfully installed dotnet in version 6.0.428

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
Internal error: Undefined error handling THROW_CLI
Running command '/Users/Username/IdeasyTestProjects/_ide/software/default/dotnet/dotnet/6.0.428/dotnet'
failed with exit code 129!
Step 'ide (dotnet)' failed: com.devonfw.tools.ide.cli.CliProcessException: Running command '/Users/Username/IdeasyTestProjects/_ide/software/default/dotnet/dotnet/6.0.428/dotnet'
failed with exit code 129!
1 step(s) failed out of 2 steps.
Running command '/Users/Username/IdeasyTestProjects/_ide/software/default/dotnet/dotnet/6.0.428/dotnet'
failed with exit code 129!

Error: IDEasy failed with exit code 129
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. 

### Affected version:

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by hohwille** [comment] 2024-12-20 16:43
This is not a bug:
You are calling `dotnet` without any further arguments.
This is giving you the usage output and a non successful exit code since `dotnet` CLI requires additional arguments.
If you instead e.g. call this it works
```
$ ide dotnet --version
6.0.428
```
There is no error here, hence I am closing this as invalid.

**Closed by hohwille** 2024-12-20 16:43 UTC
Labels: bug, macOS
