### ISSUE TITLE
Adjusting Intellij settings in ide-settings

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/IDEasy#52] opened 2023-09-28 09:36 UTC
As an Intellij user, I want to use Intellij with defaults that make sense to us. To do this, the required settings should be stored in the ide-settings repository.

* [x] Settings - Editor - Code Style - Java - Tab "Imports": 
* [x] Class count to use import with '\*' : 999
* [x] Names count to use static import with '*': 999
* [x] Set line length to at least 160 characters (I cannot imagine that as of today any developer does not get this number of characters on his screen without the need to scroll - the restrictions limiting to 80 or later 120 characters per line come from an ancient time and the reformatting line wraps added by intellij contribute to our diff-war)
* [x] Ensure we get a Warning if JavaDoc is missing or incomplete for public and protected elements (Types, Fields, Constructors, Methods including parameters).
* [x] Activate "save actions" in Intellij (like in Eclipse to ensure the code-style is always applied and cannot be forgot on commit)
* [x] Eclipse reformat plugin should not be used anymore - we want to configure IntelliJ natively (otherwise you get errors if you never installed and configured Eclipse and our team is not using eclipse) See here
https://github.com/devonfw/ide-settings/blob/d1a7dd1f1ae817b3fb659f92a8fb54eb567b3b74/intellij/plugins/EclipseCodeFormatter.properties#L2
* [x] `Optional`: ~FolderCompact plugin could be pre-installed too~ (I initially liked this plugin but it has some severe downsides - if it is installed, you do not see folders like `src` anymore and if you have ` src/main/assembly` or anything not common you get unable to see this in IntelliJ. This renders the plugin useless even though it would otherwise be great. See my rating comment [here](https://plugins.jetbrains.com/plugin/18189-foldercompact))
* [x] Maven Builder settings need to be pre-configured
* [x] Encoding for resource bundle properties to UTF-8
* more?

**Comment by jan-vcapgemini** [comment] 2023-10-04 13:39
For `Adapter for Eclipse Code Formatter` we need to use these settings:

![image](https://github.com/devonfw/IDEasy/assets/59438728/0032b6c5-a632-4b13-b809-ab486d8de43b)

**Comment by jan-vcapgemini** [comment] 2023-10-04 13:43
For the `Maven Runner` I'd suggest these settings:

![image](https://github.com/devonfw/IDEasy/assets/59438728/cb7b8f64-5006-4310-a8ce-266ea2b0e32c)

**Comment by jan-vcapgemini** [comment] 2023-10-04 13:44
For `Maven Running Tests` I'm using:

![image](https://github.com/devonfw/IDEasy/assets/59438728/cd4f96d6-4afb-42cf-82c6-8c8ad46a12e5)

**Comment by jan-vcapgemini** [comment] 2023-10-04 14:20
I've added a new branch to ide-settings now: https://github.com/devonfw/ide-settings/tree/dev-ide-settings

**Comment by jan-vcapgemini** [comment] 2023-10-09 10:10
I've realized that "Save Actions Tool" is deprecated. It won't work in the latest version of intellij anymore.
Looks like we have to remove it from our settings. :(
With some luck, we might get its features integrated into intellij later: https://youtrack.jetbrains.com/issue/IDEA-326980

**Comment by jan-vcapgemini** [comment] 2024-01-16 14:38
It looks like some more steps are required so that our settings work properly.
F.e. eclipse needs to be pre-installed automatically, otherwise our `Adapter for Eclipse Code Reformatter` Plug-In won't work at all.

We also need to make sure that our IDEasy project gets cloned and imported into intellij properly.

Current workflow looks like the following:

- manually clone IDEasy into workspaces/main
- run devon intellij
- open/import the workspaces/main folder
- browse to the IDEasy module
- rightclick on the `pom.xml` in the root and choose `Add as Maven project`

All of these steps should be run automatically.

**Comment by jan-vcapgemini** [comment] 2024-01-16 14:42
Another issue I've found is the initial clone of the settings when providing the dev-ide-settings git repository URL.
It seems like devonf-ide changed some files in the settings directory and fails to pull the latest version of our dev-ide-settings.

**Comment by hohwille** [comment] 2024-01-19 13:45
I would propose to change margin/line-length to 160 as we have in Eclipse:
https://github.com/devonfw/ide-settings/blob/7d8a9c83ad87b5d0aa060001cfd228b95605ea3f/intellij/workspace/update/.intellij/config/codestyles/Default.xml#L22

Effect:
https://github.com/devonfw/IDEasy/pull/184/files#diff-63fb5fa0581be336809a98949d6475569b657b1a3183405ac5553adacd061eda

**Comment by hohwille** [comment] 2024-01-23 13:27
Also I want to get `@Override` annotations automatically. I could not figure out how to do this with IntelliJ.
In Eclipse we have this via Save-Actions.

**Comment by mvomiero** [comment] 2024-03-21 08:44
All open tasks _(except FolderCompact, since I understood the downside is quite limiting)_ **should be solved by** https://github.com/devonfw/ide-settings/pull/38

**Comment by hohwille** [comment] 2024-03-22 15:53
Confirmed that line wrapping to 160 worked. Thanks @mvomiero 
![image](https://github.com/devonfw/IDEasy/assets/1923119/ecc59893-22e3-4a79-ae7f-8ac4595e942a)

**Comment by hohwille** [comment] 2024-03-22 15:54
@mvomiero Also Java used for maven seems correct:
![image](https://github.com/devonfw/IDEasy/assets/1923119/05b87bff-85cb-4f65-901b-5c8890fd7c43)

**Comment by hohwille** [comment] 2024-03-22 15:57
For the record:
Java is still preconfigured correctly (on Windows or without the current workaround for Mac):
![image](https://github.com/devonfw/IDEasy/assets/1923119/51c33141-2ce5-4151-9886-d8dad9c3ae36)

However, the JDK is still not pre-selected automatically:
![image](https://github.com/devonfw/IDEasy/assets/1923119/bc1d874d-d23b-44ad-b640-2bfe2a220234)

@ndemirca could you create a PR adding the `misc.xml` config that will fix this?

**Comment by hohwille** [comment] 2024-03-22 16:01
@mvomiero I still do not get warnings for missing JavaDoc:
![image](https://github.com/devonfw/IDEasy/assets/1923119/36ca9e5a-0ad4-469a-98d1-464181d47e8d)

**Comment by hohwille** [comment] 2024-03-22 16:05
@mvomiero thanks also for fixing encoding. Seems to work:
![image](https://github.com/devonfw/IDEasy/assets/1923119/c610980a-2866-42e5-bc22-8768a177046d)
(also note the yellow/orange mark if someone wants to do a quick and simple nice-to-have improvement)

**Comment by mvomiero** [comment] 2024-03-22 16:12
> @mvomiero I still do not get warnings for missing JavaDoc: ![image](https://private-user-images.githubusercontent.com/1923119/316089332-36ca9e5a-0ad4-469a-98d1-464181d47e8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjM2OTAsIm5iZiI6MTcxMTEyMzM5MCwicGF0aCI6Ii8xOTIzMTE5LzMxNjA4OTMzMi0zNmNhOWU1YS0wYWQ0LTQ2OWEtOThkMS00NjQxODFkNDdlOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTYwMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRjMWU4NTg5NjMxNGI1OTRhNmJiOGRkMmE5N2U4NThhOTA4MWVlY2QyZWVjMWMxNzFkMmIwNWU1ZjczMjM0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TiZM80yZeM3izjDK4utc0TPbePtiMCEY3OlRrGxU03E)

That is because I used the settings that were provided in `.intellij/config/inspectionProfiles/Project_Default.xml`. I used them since they seemed to be quite precise about the handling of the warnings and so on, don´t actually know who wrote them, I thought they were project-specific.

Otherwise we can just activate a normal warining for missing javadocs 📄 

* `.intellij/config/inspectionProfiles/Project_Default.xml` :
```
 <inspection_tool class="MissingJavadoc" enabled="true" enabled_by_default="false" level="WARNING">
      <scope enabled="true" level="WARNING" name="Production">
        <option name="TOP_LEVEL_CLASS_SETTINGS">
          <Options>
            <option name="MINIMAL_VISIBILITY" value="package"/>
            <option name="REQUIRED_TAGS" value="@param"/>
          </Options>
        </option>
        <option name="INNER_CLASS_SETTINGS">
          <Options>
            <option name="MINIMAL_VISIBILITY" value="private"/>
          </Options>
        </option>
        <option name="METHOD_SETTINGS">
          <Options>
            <option name="MINIMAL_VISIBILITY" value="protected"/>
            <option name="REQUIRED_TAGS" value="@return@param@throws or @exception"/>
          </Options>
        </option>
      </scope>
    </inspection_tool>

**Comment by mvomiero** [comment] 2024-03-25 15:08
I added the warning for missing JavaDoc ⚠️ 
I substituted the  not-working too specific old one in `.intellij/config/inspectionProfiles/Project_Default.xml` with a more generic in  `.intellij/config/inspection/Default.xml`

here is the related PR: https://github.com/devonfw/ide-settings/pull/41

**Comment by hohwille** [comment] 2024-04-25 13:34
I have another demand:
When running JUnit tests projects often get the "commandline too long" error what is really annoying.
I do not know, why IntelliJ is behaving so bad out-of-the-box but there is a generic solution for the problem that I will illustrate with a screenshot how it can be solved manually in the preferences:
![image](https://github.com/devonfw/IDEasy/assets/1923119/15a419b5-f7f2-49da-8f3a-f9c81a760813)
We need to apply this manually then figure out in which config files this is written and then add the needed changes to our settings repo to automate this configuration to make IntelliJ usable for Java developers.

**Comment by mvomiero** [comment] 2024-06-14 14:02
Created a new pull request:
https://github.com/devonfw/ide-settings/pull/49
that should fix the last two problems of this issue: 
* the "commandline too long" error when running JUnit tests
* missing @Override annotations

With these solved, the issue should be finally solved and could be closed 🚀

**Comment by hohwille** [comment] 2024-06-14 14:59
I do not understand what is going on but I have the impression that we are still far away from our goal.
I am on the latest main of our ide-settings and I did re-create my workspace from scratch to verify that its not my personal fault but I am getting this as a result:
![image](https://github.com/devonfw/IDEasy/assets/1923119/50cc3b45-6796-424c-b466-9cbd5351f0de)
and also this
![image](https://github.com/devonfw/IDEasy/assets/1923119/dfbb2471-8ab7-45dc-9b63-a43a1bd6edce)

So it seems that our efforts in taming IntelliJ are somehow not paying off. This is really annoying.
Is there something I could do wrong?
```
hohwille@CE49454 MSYS /d/projects/IDEasy/settings (main)
$ git log
commit 476b4e70b8690b0f6e22b3f332a285e0446edbc1 (HEAD -> main, origin/main)
Author: jan-vcapgemini <59438728+jan-vcapgemini@users.noreply.github.com>
Date:   Mon May 6 17:13:24 2024 +0200

    devonfw/IDEasy#154: show project name in intellij (#44)
```

**Comment by hohwille** [comment] 2024-06-14 15:02
Seems I am forced to temporary go back to Eclipse since I am blocked and do not want to waste my time with this crappy IntelliJ that always gets into my way.

**Comment by mvomiero** [comment] 2024-06-19 09:06
@hohwille I think the problem is that you are on branch `main` and not `dev-ide-settings` 😃
I believe we were speaking about merging the two branches some time ago right? but at the end it never happened.

**Comment by hohwille** [comment] 2024-06-20 17:00
> @hohwille I think the problem is that you are on branch `main` and not `dev-ide-settings` 😃 I believe we were speaking about merging the two branches some time ago right? but at the end it never happened.

I created and merged https://github.com/devonfw/ide-settings/pull/50 to avoid such problems and confusions.

**Comment by hohwille** [comment] 2024-07-09 09:29
There is a simple option for the undesired reformatting of single-line JavaDoc comments causing Diff-Wars:
![7aUur](https://github.com/devonfw/IDEasy/assets/1923119/245aeb49-abdd-4fc4-a73e-4ecc521c8b9a)

**Comment by hohwille** [comment] 2024-07-09 09:51
It seems to be already configured this way:
https://github.com/devonfw/ide-settings/blob/5a4f6e225131ad6cfcb035ee1e383fc3f1d3c1e2/intellij/workspace/update/.intellij/config/codestyles/Default.xml#L9

However, what we configure sometimes does not apply.
I have some doubts about how our config looks like...
Why do we have some of these settings in `<JavaCodeStyleSettings>` while others are in `<codeStyleSettings language="JAVA">`? Is that all some IntelliJ legacy that is really required or are we maybe doing something wrong in our XML structure. Maybe we have to configure this from scratch in an IntelliJ not managed by IDEasy and then create our template from that outcome. In the worst case the XML structure has to be different for various versions of IntelliJ and then we are lost with the approach.

We have already discussed a very long time ago that it would be much smart to do all this with a simple `.editorconfig` file instead and ignore the native XML config used by IntelliJ that is undocumented. The `.editorconfig` is a more stable "API" to configure IntelliJ more "officially".

**Comment by hohwille** [comment] 2024-07-12 11:08
![image](https://github.com/user-attachments/assets/bb3f085a-32ff-44d7-bdaf-9dfe9f82911e)

**Comment by hohwille** [comment] 2024-08-13 13:42
Can https://github.com/devonfw/ide-settings/blob/main/intellij/workspace/setup/.idea/saveactions_settings.xml be deleted? Seems not relevant anymore.

**Comment by hohwille** [comment] 2024-08-13 13:43
Please create issue for XML merger usage of intellij XML configs and move them from `setup` to `update.

**Comment by jan-vcapgemini** [comment] 2024-09-09 16:48
> @mvomiero Also Java used for maven seems correct: ![image](https://private-user-images.githubusercontent.com/1923119/316086763-05b87bff-85cb-4f65-901b-5c8890fd7c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzM1NjAsIm5iZiI6MTcyNTg3MzI2MCwicGF0aCI6Ii8xOTIzMTE5LzMxNjA4Njc2My0wNWI4N2JmZi04NWNiLTRmNjUtOTAxYi01Yzg4OTBmZDdjNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMDkxNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYyOTZhNDA5MjNiYjAzMDc1YTVkMTY5NDc4OWRhNWNhYzYyZjBlNzJhZjlkMDE4ZmY2ZmM1ZTJkMTEzYWIzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tgep31rl6szFDCLE0hhMJ8PThc45QCgWlDEJAMT4WH4)

Added new issue for this behaviour: https://github.com/devonfw/IDEasy/issues/601

**Comment by jan-vcapgemini** [comment] 2024-09-09 16:57
All open points of this issue were addressed and for the current bugs new issues were created. This issue can be closed now.

**Closed by jan-vcapgemini** 2024-09-09 16:57 UTC
Labels: enhancement
