### ISSUE TITLE
Synchronize import orders of Eclipse and Intellij

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#460] opened 2024-07-09 08:35 UTC
As an IDEasy user I expect that my code reformats will work similar in all IDEs.
Currently the order of the java class imports differ in Eclipse and Intellij.
We need to make sure that they are the same.

**Comment by hohwille** [comment] 2024-08-01 13:12
IMHO now a duplicate of #465 since I have already done this in our existing `.editorconfig` file.

**Closed by hohwille** 2024-08-01 13:12 UTC
Labels: enhancement, eclipse, intellij
