### ISSUE TITLE
Paths not formatted correctly when running env after env --bash in the shell

### ISSUE THREAD

**Issue by slskiba** [devonfw/IDEasy#383] opened 2024-06-05 12:47 UTC
### Expected behavior

As a windows user, I want `env` to provide windows-style paths

### Actual behavior

If called after `env --bash` in the shell, succeeding `env` still formats paths in unix-style

### Steps to reproduce (bug)

1. Start the ide shell
2. Run `env`. Output, as expected: 
```
ide> env
export PATH="C:\projects\IDEasy\  [...]
```
3. Run `env --bash`. Output, as expected: 
```
ide> env --bash
export PATH="/c/projects/IDEasy/  [...]
```
4. Run `env`. Output not as expected. It is the same output as step 2, however should be the same to step 1. 
```
ide> env --bash
export PATH="/c/projects/IDEasy/  [...]
```

### Comments/Hints:

The `FlagProperty bash` of the `EnvironmentCommandlet` will always be present as true, once it is set for the first time when running it from the ide shell.

**Comment by hohwille** [comment] 2024-06-14 12:06
Isnt this a duplicate of #321 that can be closed?

**Closed** 2024-06-14 16:00 UTC
Labels: bug

**Comment by slskiba** [comment] 2024-06-14 16:31
> Isnt this a duplicate of #321 that can be closed?

No, it was in fact a seperate issue, but has been fixed as part of https://github.com/devonfw/IDEasy/pull/381#issuecomment-2165123605
