### ISSUE TITLE
Git clone hangs in initial project

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#277] opened 2024-04-04 09:20 UTC
### Expected behavior

As an IDEasy user I expect that my `git clone` works without issues.

### Actual behavior
If a new project was initialized and IDEasy tries to clone the urls repository, the `clone` command starts and hangs forever.
After starting another IDEasy process, it runs fine.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a new Project (using devonfw-ide as base project)
2. Run IDEasy with -t and a toolcommandlet f.e. `IDEasy -t az`
3. Wait for the `clone` process to start

### Comments/Hints:
Could be caused by the non-parallel capture of output and error messages.

### Affected version:

* IDEasy dev-SNAPSHOT

**Comment by hohwille** [comment] 2024-04-05 12:07
This issue is somehow a duplicate of #6

**Closed** 2024-04-05 12:07 UTC
Labels: bug
